name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  format-check:
    name: Check Mix Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.19
          otp-version: 28

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Check code format
        run: mix format --check-formatted

  credo-check:
    name: Check Mix Credo Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.18
          otp-version: 28

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Run Credo Linter
        run: mix credo --strict --format=flycheck

  docs-check:
    name: Check Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.19
          otp-version: 28

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Generate docs
        run: mix docs --warnings-as-errors

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - format-check
      - credo-check
      - docs-check
    strategy:
      matrix:
        include:
          - elixir: 1.19
            otp: 28
          - elixir: 1.18
            otp: 27
          - elixir: 1.17
            otp: 26
          - elixir: 1.16
            otp: 25
          - elixir: 1.15
            otp: 24
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: |
            plt-test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
          path: |
            priv/plts

      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: MIX_ENV=test mix dialyzer --plt

      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v3
        if: steps.plt_cache.outputs.cache-hit != 'true'
        with:
          key: |
            plt-test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          path: |
            priv/plts

      - name: Run Tests
        run: mix test --include dialyzer --warnings-as-errors

  dialyzer:
    name: Run Dialyzer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.19
            otp: 28
    needs:
      - format-check
      - credo-check
      - docs-check
    steps:
      - uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: |
            plt-dev-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-dev-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
          path: |
            priv/plts

      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v3
        if: steps.plt_cache.outputs.cache-hit != 'true'
        with:
          key: |
            plt-dev-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          path: |
            priv/plts

      - name: Run Dialyzer
        run: mix dialyzer
